version: 2.1 # CircleCI syntax version
jobs: # a collection of steps
  build: # runs that are not using Workflows must have a `build` job as the entry point
    docker: # run the steps with Docker
      - image: circleci/node:9.9.0 # ...with this image as the primary container;
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-tools
          command: sudo npm install -g grunt-cli mocha nyc electron --unsafe-perm=true --allow-root
      - run:
          name: install-new-modules
          command: sudo npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: 
            git push https://git.heroku.com/ci-cd-test-24601.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
